### ISSUE TITLE
Liste de films

### ISSUE THREAD

**Issue by xercasy** [etienne-gauvin/api-allocine-helper#23]
Bonjour,

Je n'ai pas encore vraiment commencé à utilisé cet API mais au bout de quelques jours de recherches je ne trouve toujours pas comment faire une requête pour récuperer une liste de film en fonction de son genre ...
Donc finalement je me dis qu'on ne peut pas le faire mais je tiens quand même à en être sur
Merci

**Comment by etienne-gauvin** [comment]
Bonjour xercasy,
En effet, ce n'est pas possible :/
