### ISSUE TITLE
Erreur 403 avec search

### ISSUE THREAD

**Issue by unrealkill78** [etienne-gauvin/api-allocine-helper#28]
$allohelper->search

Renvoie une erreur 403 qui provoque : Erreur 5: Object reference not set to an instance of an object.

**Comment by kidseb12** [comment]
Pareil pour moi concernant la recherche car pour la récuperation via le code film elle fonctionne bien et recupere bien les infos

**Comment by unrealkill78** [comment]
Le problème à l'air d'être résolu
